# Trigger this workflow from the command line with:
# gh api /repos/:owner/:repo/actions/workflows/zen.yml/dispatches --field ref=main
name: Zen

on:
  workflow_dispatch:

jobs:
  zen:
    name: Zen
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add zen
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "$( gh api zen )" >> zen.txt
        cat zen.txt

    - name: Commit zen
      id: commit
      uses: swinton/commit@v2.x
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          zen.txt
        commit-message: Add more zen

    - name: Echo commit SHA
      env:
        MY_COMMIT_SHA: ${{ steps.commit.outputs.commit-sha }}
      run: |
        echo "https://github.com/$GITHUB_REPOSITORY/commit/$MY_COMMIT_SHA" has been created
